spring:
  application:
    name: restaurant-service

  cloud:
    openfeign:
      client:
        config:
         default: 
           connectTimeout: 5000
           readTimeout: 5000
           loggerLevel: full

         user-service:
            url: http://localhost:8081
         traceability-service: 
            url: http://localhost:8082
         courier-service:
            url: http://localhost:8083

  datasource:
    url: jdbc:postgresql://localhost:5432/<db>
    username: postgres
    password: <password>
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

my-app:
  security:
    jwt:
      secret-key: aa51197e3861ba9d8e7d3add5f2bc30862c891e0a3762935c8b8ecf6a61a9994
    
server:
  port: 8080


logging:
  level:
    org:
      springframework:
        security: DEBUG


springdoc:
  swagger-ui:
    path: /swagger-ui.html